### ISSUE TITLE
Allow multiple input files and/or directories

### ISSUE THREAD

**Issue by xgc1986** [j13k/yaml-lint#3]
I've just created a git hook and I have to call the binary foreach file, I would prefer to call it with all files I want to check.

**edit**: I've seen that already does that, may I have a problem in my hook, but if I have multiples wrong yaml files, it only tells me what is wrong with one file

Good project, I was looking for a yaml linter I could install with composer

**Comment by j13k** [comment]
Thanks for the suggestion — that sounds like it could be a useful feature to add.

Currently I lint multiple files using `find` with `xargs`, however being able to execute within a git hook would be useful.

Could you give me an example of the hook script you're using?

**Comment by xgc1986** [comment]
That is the code
FYI gitamine f:c returns a list with the files that are being commited, those files are which later i am checking with your linter

`#!/usr/bin/env bash

FILES="$(gitamine f:c | grep -E "(\.yaml$|\.yml$)" | tr '\r\n' ' ')"
LINES="$(echo ${FILES} | wc -c)"
if [ "$LINES" -gt "1" ]
then
    bin/yaml-lint ${FILES}
fi
`

**Comment by OndraM** [comment]
Hi, I just came across probably the same issue. I have lint step on my CI defined as `vendor/bin/yaml-lint *.yml`. But only the first matched yaml file was linted, even though the pattern is expanded to multiple files. Also this produces no warning, so I mistakenly assumed all my yml files are being linted...

**Comment by j13k** [comment]
Hi @OndraM, thanks for your comment — I can see that this is a more serious issue than I first realised.

I need to carve out some time to upgrade the tool with multi-file support — it's not a difficult change, but now that the tool is seeing a fair bit of usage, and has to support multiple PHP and Symfony Yaml versions, I also want to set up adequate test coverage before undertaking non-trivial changes.

Because of this, I've created a separate issue (https://github.com/j13k/yaml-lint/issues/7) to track the need for a patch in the short term.

I can see that you've worked around the issue in your project — the style of file iteration you've used is how I've typically invoked the tool in my own CI setup.
