### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by wow-apps** [j13k/yaml-lint#45]
Symfony 6 is now stable and we need yaml-lint support for it )

**Comment by j13k** [comment]
Fixed in #46.

**Comment by oallain** [comment]
Hello @j13k 

Can you make a new tag ?

Regards

**Comment by davereid** [comment]
Agreed, a new tagged release would be useful. This is becoming a blocker to continuing to use this project as a result.

**Comment by j13k** [comment]
@oallain, @davereid a new release, [1.1.5](https://github.com/j13k/yaml-lint/releases/tag/1.1.5), has been minted with Symfony 6 support included. 

Thanks for your patience with this: given the usage of this project has grown substantially since the last release, I wanted to take some time to set up some tests before releasing. These are now in place as well.

**Comment by oallain** [comment]
> FYI @wow-apps, @oallain, @davereid a new release, [1.1.5](https://github.com/j13k/yaml-lint/releases/tag/1.1.5), has been minted with Symfony 6 support included.
> 
> Thanks for your patience with this: given the usage of this project has grown substantially since the last release, I wanted to take some time to set up some tests before releasing. These are now in place as well.

Thanks for that 🥳
